# Generated by Django 5.0.3 on 2024-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=15)),
                ('user_mname', models.CharField(max_length=15)),
                ('user_lname', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=20, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
